<?php

class WaP_Protection
{

    public function check_access_rules($result)
    {
        // If an error has already been generated by another plugin, return it.
        if (is_wp_error($result)) {
            return $result;
        }

        // 1. Whitelist Check
        if ($this->is_ip_whitelisted()) {
            return true; // Grant access (bypasses other authentication checks if this filter handles it, or just passes through)
            // returning true in rest_authentication_errors typically enables access publicly if no other auth method intercedes.
            // Better to return $result (null) to allow normal authentication if we just want to "not block".
            // But if we want to "allow" like a whitelist, we might accept it.
            // For now, let's return $result so valid credentials are still required? 
            // The user said "Whitelist IP". Usually means "Allow this IP to bypass blocks".
            // Let's return $result.
            return $result;
        }

        // 2. Admin/User Check
        if (current_user_can('manage_options')) {
            return $result;
        }

        // 3. Hard Block Mode (Optional)
        // If "Private Site" mode is enabled, reject everyone else.
        $hard_block = get_option('wap_hard_block_enabled', false);
        if ($hard_block) {
            return new WP_Error(
                'wap_restricted_access',
                __('API Access Restricted to Whitelisted IPs and Admins.', 'wp-api-protection'),
                array('status' => 403)
            );
        }

        return $result;
    }

    private function is_ip_whitelisted()
    {
        $whitelist_raw = get_option('wap_whitelist_ips', '');
        if (empty($whitelist_raw))
            return false;

        $ips = array_map('trim', explode("\n", $whitelist_raw));
        $user_ip = $_SERVER['REMOTE_ADDR'];

        return in_array($user_ip, $ips);
    }

    /**
     * Blocks user enumeration via ?author=N or /author/name archives.
     */
    public function block_author_scanning()
    {
        // Allow admins to see authors
        if (current_user_can('manage_options')) {
            return;
        }

        // Check if viewing an author archive or using the author query var
        if (is_author() || isset($_GET['author'])) {
            wp_redirect(home_url());
            exit;
        }
    }
}
