<?php

class WaP_Protection
{

    public function check_access_rules($result)
    {
        // If an error has already been generated by another plugin, return it.
        if (is_wp_error($result)) {
            return $result;
        }

        // 1. Whitelist Check
        if ($this->is_ip_whitelisted()) {
            return true; // Grant access (bypasses other authentication checks if this filter handles it, or just passes through)
            // returning true in rest_authentication_errors typically enables access publicly if no other auth method intercedes.
            // Better to return $result (null) to allow normal authentication if we just want to "not block".
            // But if we want to "allow" like a whitelist, we might accept it.
            // For now, let's return $result so valid credentials are still required? 
            // The user said "Whitelist IP". Usually means "Allow this IP to bypass blocks".
            // Let's return $result.
            return $result;
        }

        // 2. Admin/User Check
        if (current_user_can('manage_options')) {
            return $result;
        }

        // 3. Hard Block Mode (Optional)
        // If "Private Site" mode is enabled, reject everyone else.
        $hard_block = get_option('wap_hard_block_enabled', false);
        if ($hard_block) {

            // Log the block
            if (class_exists('WaP_Logger')) {
                WaP_Logger::log($_SERVER['REMOTE_ADDR'], 'Hard Block', 'Private Site Mode Active');
            }

            // TROLL MODE CHECK (Added Fix)
            if (get_option('wap_troll_mode_enabled', false)) {
                $this->serve_troll_response();
            }

            return new WP_Error(
                'wap_restricted_access',
                __('API Access Restricted to Whitelisted IPs and Admins.', 'wp-api-protection'),
                array('status' => 403)
            );
        }

        return $result;
    }

    private function is_ip_whitelisted()
    {
        $whitelist_raw = get_option('wap_whitelist_ips', '');
        if (empty($whitelist_raw))
            return false;

        $ips = array_map('trim', explode("\n", $whitelist_raw));
        $user_ip = $_SERVER['REMOTE_ADDR'];

        return in_array($user_ip, $ips);
    }

    /**
     * Blocks user enumeration via ?author=N or /author/name archives.
     */
    /**
     * Blocks user enumeration via ?author=N or /author/name archives.
     */
    public function block_author_scanning()
    {
        // Allow admins to see authors
        if (current_user_can('manage_options')) {
            return;
        }

        // Check if viewing an author archive or using the author query var
        if (is_author() || isset($_GET['author'])) {

            // Check for Troll Mode
            if (get_option('wap_troll_mode_enabled', false)) {
                $this->serve_troll_response();
            }

            wp_redirect(home_url());
            exit;
        }
    }

    /**
     * Identifies if the request comes from a CLI tool (curl, wget, etc).
     */
    private function is_cli_request()
    {
        $ua = isset($_SERVER['HTTP_USER_AGENT']) ? strtolower($_SERVER['HTTP_USER_AGENT']) : '';
        $cli_tools = array('curl', 'wget', 'python', 'nmap', 'sqlmap', 'nikto', 'gobuster');

        foreach ($cli_tools as $tool) {
            if (strpos($ua, $tool) !== false) {
                return true;
            }
        }
        return false;
    }

    /**
     * Serves the prank response based on client type.
     */
    public function serve_troll_response()
    {
        if ($this->is_cli_request()) {
            // CLI Response
            header('X-Hacker-Rank: Noob');
            header('X-Trolled-By: WP API Protection');
            header('Content-Type: text/plain');

            echo "\n";
            echo "   /\\_/\\  \n";
            echo "  ( o.o ) \n";
            echo "   > ^ <  \n";
            echo "  HACKER DETECTADO!\n\n";
            echo "  Buen intento, pero hoy no.\n";
            echo "  Intenta hackear a tu abuela mejor.\n\n";
            die();
        } else {
            // Browser Response (Mr. Robot Style)
            $ip = $_SERVER['REMOTE_ADDR'];

            echo '<!DOCTYPE html><html><head><title>INTRUSION DETECTED</title>';
            echo '<style>body{background:#000;color:#0f0;font-family:monospace;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;overflow:hidden;}';
            echo '.term{width:80%;max-width:800px;} h1{color:red;font-size:3em;animation:blink 1s infinite;}';
            echo '@keyframes blink{50%{opacity:0;}}</style>';
            echo '</head><body><div class="term">';
            echo '<h1>⚠️ INTRUSION DETECTED ⚠️</h1>';
            echo "<p>> TRACING SOURCE IP... [DONE]</p>";
            echo "<p>> TARGET IDENTIFIED: <strong style='color:red;font-size:1.5em;'>$ip</strong></p>";
            echo "<p>> UPLOADING LOGS TO INTERPOL CYBERCRIME UNIT...</p>";
            echo "<p id='upload'>[||||||||||-----] 78%</p>";
            echo "<script>setInterval(function(){ document.getElementById('upload').innerText = '[|||||||||||||||] 100% - UPLOAD COMPLETE'; }, 2000);</script>";
            echo '</div></body></html>';
            die();
        }
    }
}
