<?php

class WaP_Protection
{

    public function check_access_rules($result)
    {
        // If an error has already been generated by another plugin, return it.
        if (is_wp_error($result)) {
            return $result;
        }

        // 1. Whitelist Check
        if ($this->is_ip_whitelisted()) {
            return true; // Grant access (bypasses other authentication checks if this filter handles it, or just passes through)
            // returning true in rest_authentication_errors typically enables access publicly if no other auth method intercedes.
            // Better to return $result (null) to allow normal authentication if we just want to "not block".
            // But if we want to "allow" like a whitelist, we might accept it.
            // For now, let's return $result so valid credentials are still required? 
            // The user said "Whitelist IP". Usually means "Allow this IP to bypass blocks".
            // Let's return $result.
            return $result;
        }

        // 2. Admin/User Check
        if (current_user_can('manage_options')) {
            return $result;
        }

        // 3. Hard Block Mode (Optional)
        // If "Private Site" mode is enabled, reject everyone else.
        $hard_block = get_option('wap_hard_block_enabled', false);
        if ($hard_block) {

            // Log the block
            if (class_exists('WaP_Logger')) {
                WaP_Logger::log($_SERVER['REMOTE_ADDR'], 'Hard Block', 'Private Site Mode Active');
            }

            // TROLL MODE CHECK (Added Fix)
            if (get_option('wap_troll_mode_enabled', false)) {
                $this->serve_troll_response();
            }

            return new WP_Error(
                'wap_restricted_access',
                __('API Access Restricted to Whitelisted IPs and Admins.', 'wp-api-protection'),
                array('status' => 403)
            );
        }

        return $result;
    }

    private function is_ip_whitelisted()
    {
        $whitelist_raw = get_option('wap_whitelist_ips', '');
        if (empty($whitelist_raw))
            return false;

        $ips = array_map('trim', explode("\n", $whitelist_raw));
        $user_ip = $_SERVER['REMOTE_ADDR'];

        return in_array($user_ip, $ips);
    }

    /**
     * Blocks user enumeration via ?author=N or /author/name archives.
     */
    /**
     * Blocks user enumeration via ?author=N or /author/name archives.
     */
    public function block_author_scanning()
    {
        // Allow admins to see authors
        if (current_user_can('manage_options')) {
            return;
        }

        // Check if viewing an author archive or using the author query var
        if (is_author() || isset($_GET['author'])) {

            // Check for Troll Mode
            if (get_option('wap_troll_mode_enabled', false)) {
                $this->serve_troll_response();
            }

            wp_redirect(home_url());
            exit;
        }
    }

    /**
     * Identifies if the request comes from a CLI tool (curl, wget, etc).
     */
    private function is_cli_request()
    {
        $ua = isset($_SERVER['HTTP_USER_AGENT']) ? strtolower($_SERVER['HTTP_USER_AGENT']) : '';
        $cli_tools = array('curl', 'wget', 'python', 'nmap', 'sqlmap', 'nikto', 'gobuster');

        foreach ($cli_tools as $tool) {
            if (strpos($ua, $tool) !== false) {
                return true;
            }
        }
        return false;
    }

    /**
     * Serves the prank response based on client type.
     */
    /**
     * Serves the prank response based on client type.
     */
    public function serve_troll_response()
    {
        if ($this->is_cli_request()) {
            // CLI Response
            header('X-Hacker-Rank: Noob');
            header('X-Trolled-By: WP API Protection');
            header('Content-Type: text/plain; charset=utf-8');

            echo "\n";
            echo "   /\\_/\\  \n";
            echo "  ( o.o ) \n";
            echo "   > ^ <  \n";
            echo "  HACKER DETECTADO!\n\n";
            echo "  Buen intento, pero hoy no.\n";
            echo "  Intenta hackear a tu abuela mejor.\n\n";
            die();
        } else {
            // Browser Response (Randomized PsyOps)
            $ip = $_SERVER['REMOTE_ADDR'];
            $ua = $_SERVER['HTTP_USER_AGENT'];
            // Try to get country from transient if available (from Geo Block check)
            $country = get_transient('wap_geo_' . md5($ip)) ?: 'Unknown';

            // 50% Chance of Divine Mirror (Biblical) vs Mr. Robot (Cyber)
            if (rand(0, 1) === 0) {
                // THEME 1: DIVINE MIRROR (El Espejo Divino)
                ?>
                                <!DOCTYPE html>
                                <html>
                                <head>
                                    <title>👁️ NADA ESTÁ OCULTO</title>
                                    <style>
                                        body { background-color: #0d0d0d; color: #c0c0c0; font-family: 'Georgia', serif; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0; text-align: center; }
                                        .container { max-width: 600px; padding: 40px; border: 1px solid #333; box-shadow: 0 0 50px rgba(255, 255, 255, 0.05); }
                                        h1 { font-size: 2.5em; color: #fff; letter-spacing: 5px; margin-bottom: 20px; text-transform: uppercase; }
                                        p { font-size: 1.1em; line-height: 1.6; color: #888; }
                                        .data-table { margin-top: 30px; text-align: left; background: #111; padding: 20px; border-left: 3px solid #666; font-family: 'Courier New', monospace; }
                                        .label { color: #555; font-weight: bold; }
                                        .value { color: #ddd; }
                                    </style>
                                </head>
                                <body>
                                    <div class="container">
                                        <h1>El Espejo Divino</h1>
                                        <p>"Porque no hay nada oculto que no haya de ser manifestado; ni escondido, que no haya de salir a luz." (Marcos 4:22)</p>
                                        <p>Tu intento ha sido registrado. Tu identidad es conocida.</p>
                        
                                        <div class="data-table">
                                            <div><span class="label">IP Detectada:</span> <span class="value"><?php echo esc_html($ip); ?></span></div>
                                            <div><span class="label">Ubicación:</span> <span class="value"><?php echo esc_html($country); ?></span></div>
                                            <div><span class="label">User-Agent:</span> <span class="value"><?php echo esc_html(substr($ua, 0, 50)) . '...'; ?></span></div>
                                            <div><span class="label">Estado:</span> <span class="value" style="color: #ff4444;">REGISTRADO</span></div>
                                        </div>
                                    </div>
                                </body>
                                </html>
                                <?php
            } else {
                // THEME 2: MR. ROBOT (Cyber Warfare)
                ?>
                                <!DOCTYPE html>
                                <html>
                                <head>
                                    <title>🚫 SYSTEM FAILURE</title>
                                    <style>
                                        body { background: #000; color: #0f0; font-family: 'Courier New', monospace; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0; overflow: hidden; }
                                        .term { width: 80%; max-width: 800px; }
                                        h1 { color: #ff0000; font-size: 3em; animation: blink 1s infinite; margin-bottom: 10px; }
                                        p { margin: 5px 0; font-size: 1.2em; }
                                        @keyframes blink { 50% { opacity: 0; } }
                                        .progress { width: 100%; background: #333; height: 20px; margin-top: 20px; border: 1px solid #0f0; }
                                        .bar { width: 0%; height: 100%; background: #0f0; animation: load 4s forwards; }
                                        @keyframes load { 100% { width: 100%; } }
                                    </style>
                                </head>
                                <body>
                                    <div class="term">
                                        <h1>⚠️ SECURITY BREACH DETECTED</h1>
                                        <p>> TRACING SOURCE IP... [DONE]</p>
                                        <p>> TARGET IDENTIFIED: <strong style='color:#ff0000; font-size:1.5em;'><?php echo esc_html($ip); ?> (<?php echo esc_html($country); ?>)</strong></p>
                                        <p>> INITIATING COUNTER-MEASURES...</p>
                                        <p>> UPLOADING FORENSIC LOGS TO ADMIN...</p>
                                        <div class="progress"><div class="bar"></div></div>
                                        <p id="msg" style="margin-top:20px; color: yellow;"></p>
                                        <script>
                                            setTimeout(function(){ document.getElementById('msg').innerText = '> YOU HAVE 5 SECONDS TO DISCONNECT BEFORE ISP REPORT.'; }, 2500);
                                            setTimeout(function(){ document.body.style.background = 'red'; document.body.style.color = 'black'; }, 4500);
                                        </script>
                                    </div>
                                </body>
                                </html>
                                <?php
            }
            die();
        }
    }
}
